# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62a00b2e0e603f788c1ba906de7c9975f7220ac88a72758231702e23e7ace614d5907ee7d906734dca47de420cceafccf8bbd2912f55e8df5c81a969da21ee73

test:
  secret_key_base: bc2b9321bb810eb1918f77097c6a83db9c41ad4c70d98df1c5495025735cd304219be407244454246235b1ac6b8864ddd56fc6e225e0e19c52b6addb6ed8123f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
